config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  devise_for :users, :controllers => { 
    registrations: 'users/registrations', 
    omniauth_callbacks: "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :repositories do
    get "more", on: :collection
    put "star", on: :member
    put "unstar", on: :member
  end
  get "/", to: redirect("/repositories")


end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  # Define query for repository listing.
  #
  # All queries MUST be assigned to constants and therefore be statically
  # defined. Queries MUST NOT be generated at request time.
  IndexQuery = ConnectGitHub::Client.parse <<-'GRAPHQL'
    # All read requests are defined in a "query" operation
    query {
      # viewer is the currently authenticated User
      viewer {
        # "...FooConstant" is the fragment spread syntax to include the index
        # view's fragment.
        #
        # "Views::Repositories::Index::Viewer" means the fragment is defined
        # in app/views/repositories/index.html.erb and named Viewer.
        ...Views::Repositories::Index::Viewer
      }
    }
  GRAPHQL

  # GET /repositories
  def index
    # Use query helper defined in ApplicationController to execute the query.
    # `query` returns a GraphQL::Client::QueryResult instance with accessors
    # that map to the query structure.
    data = query IndexQuery

    # Render the app/views/repositories/index.html.erb template with our
    # current User.
    #
    # Using explicit render calls with locals is preferred to implicit render
    # with instance variables.
    render "repositories/index", locals: {
      viewer: data.viewer
    }
  end


  # Define query for "Show more repositories..." AJAX action.
  MoreQuery = ConnectGitHub::Client.parse <<-'GRAPHQL'
    # This query uses variables to accept an "after" param to load the next
    # 10 repositories.
    query($after: String!) {
      viewer {
        repositories(first: 10, after: $after) {
          # Instead of refetching all of the index page's data, we only need
          # the data for the repositories container partial.
          ...Views::Repositories::Repositories::RepositoryConnection
        }
      }
    }
  GRAPHQL

  # GET /repositories/more?after=CURSOR
  def more
    # Execute the MoreQuery passing along data from params to the query.
    data = query MoreQuery, after: params[:after]

    # Using an explicit render again, just render the repositories list partial
    # and return it to the client.
    render partial: "repositories/repositories", locals: {
      repositories: data.viewer.repositories
    }
  end


  # Define query for repository show page.
  ShowQuery = ConnectGitHub::Client.parse <<-'GRAPHQL'
    # Query is parameterized by a $id variable.
    query($id: ID!) {
      # Use global id Node lookup
      node(id: $id) {
        # Include fragment for app/views/repositories/show.html.erb
        ...Views::Repositories::Show::Repository
      }
    }
  GRAPHQL

  # GET /repositories/ID
  def show
    # Though we've only defined part of the ShowQuery in the controller, when
    # query(ShowQuery) is executed, we're sending along the query as well as
    # all of its fragment dependencies to the API server.
    #
    # Here's the raw query that's actually being sent.
    #
    # query RepositoriesController__ShowQuery($id: ID!) {
    #   node(id: $id) {
    #     ...Views__Repositories__Show__Repository
    #   }
    # }
    #
    # fragment Views__Repositories__Show__Repository on Repository {
    #   id
    #   owner {
    #     login
    #   }
    #   name
    #   description
    #   homepageUrl
    #   ...Views__Repositories__Navigation__Repository
    # }
    #
    # fragment Views__Repositories__Navigation__Repository on Repository {
    #   hasIssuesEnabled
    # }
    data = query ShowQuery, id: params[:id]

    if repository = data.node
      render "repositories/show", locals: {
        repository: repository
      }
    else
      # If node can't be found, 404. This may happen if the repository doesn't
      # exist, we don't have permission or we used a global ID that was the
      # wrong type.
      head :not_found
    end
  end
end

app/views/repositories/_icon.html.erb
<%graphql
  fragment Repository on Repository {
    isFork
    isMirror
    isPrivate
  }
%>
<% repository = Views::Repositories::Icon::Repository.new(repository) %>

<% if repository.is_fork? %>
  <span class="octicon octicon-repo-forked"></span>
<% elsif repository.is_private? %>
  <span class="octicon octicon-lock"></span>
<% elsif repository.is_mirror? %>
  <span class="octicon octicon-mirror"></span>
<% else %>
  <span class="octicon octicon-repo"></span>
<% end %>

app/views/repositories/_list_item.html.erb
<%graphql
  fragment Repository on Repository {
    id
    owner {
      login
    }
    name
    stargazers {
      totalCount
    }
    ...Views::Repositories::Icon::Repository
  }
%>
<% repository = Views::Repositories::ListItem::Repository.new(repository) %>

<li class="list-group-item">
  <span class="star-badge">
    <%= repository.stargazers.total_count %>
    <span class="octicon octicon-star"></span>
  </span>

  <%= render "repositories/icon", repository: repository %>

  <a href="<%= repository_path(repository.id) %>">
    <%= repository.owner.login %>/<%= repository.name %>
  </a>
</li>

app/views/repositories/_navigation.html.erb
<%graphql
  fragment Repository on Repository {
    hasIssuesEnabled
    issues {
      totalCount
    }
    pullRequests {
      totalCount
    }
  }
%>
<% repository = Views::Repositories::Navigation::Repository.new(repository) %>

<ul class="nav nav-pills pull-right">
  <li role="presentation" class="active">
    <a href="#">
      <span class="octicon octicon-code"></span>
      Code
    </a>
  </li>
  <%# NOTE: has_issues_enabled is snake case here. We can also include an optional `?` %>
  <% if repository.has_issues_enabled? %>
    <li role="presentation">
      <a href="#">
        <span class="octicon octicon-issue-opened"></span>
        Issues
        <span class="badge"><%= repository.issues.total_count %></span>
      </a>
    </li>
  <% end %>
  <li role="presentation">
    <a href="#">
      <span class="octicon octicon-git-pull-request"></span>
      Pull requests
      <span class="badge"><%= repository.pull_requests.total_count %></span>
    </a>
  </li>
  <li role="presentation">
    <a href="#">
      <span class="octicon octicon-pulse"></span>
      Pulse
    </a>
  </li>
  <li role="presentation">
    <a href="#">
      <span class="octicon octicon-graph"></span>
      Graphs
    </a>
  </li>
</ul>

app/views/repositories/_repositories.html.erb
<%graphql
  # Connection types are similar to ActiveRecord associations. Connections
  # always expose "edges" and "pageInfo". "edges" are the items in the
  # collection and "pageInfo" is pagination related metadata.
  fragment RepositoryConnection on RepositoryConnection {
    # edges returns an Array, however it doesn't return an Array of
    # Repositories. Instead its a RepositoryEdge that has a node that is a
    # Repository. Sorry, for all the indirection.
    edges {
      # node is the Repository itself
      node {
        ...Views::Repositories::ListItem::Repository
      }

      # Cursor is an opaque identifier that lets you fetch items before or
      # after this repository in this collection. To fetch the next 10 items,
      # we'll want the last item's cursor.
      cursor
    }

    # Pagination related metadata
    pageInfo {
      hasNextPage
      # hasPreviousPage can also be checked
    }
  }
%>
<% repositories = Views::Repositories::Repositories::RepositoryConnection.new(repositories) %>

<%#
  We could enumerate this list by repositories.edges.each { |edge| edge.node }
  but each_node provides a handy enumerator to get each repository.
%>
<% repositories.each_node do |repository| %>
  <%= render "repositories/list_item", repository: repository %>
<% end %>

<% if repositories.page_info.has_next_page? %>
  <li class="list-group-item show-more">
    <a onclick="loadMoreRepositories(event);" href="<%= more_repositories_path(after: repositories.edges.last.cursor) %>">
      Show more repositories...
    </a>
    <span class="octicon octicon-sync spinner"></span>
  </li>
<% end %>

app/views/repositories/index.html.erb
<%#
  GraphQL fragments are defined in the templates themselves.

  All data being used directly in this template should also be reflected
  statically in the fragment. And vice versa, all fields in the query fragment
  should only be used directly in this template. You MUST keep static queries
  and runtime usage in sync. Defining queries in the same file makes
  this aspect easier to manage.
%>
<%graphql
  # Fragments are parts of queries, they can't be executed themselves.
  # This fragment is defined on the User type and is named "Viewer". You can
  # name the fragment whatever you'd like. Its the name that is exported as
  # a Ruby constant, so it must start with a capital letter.
  #
  # Its exported as "Views::Repositories::Index::Viewer". The module path to
  # the tempate then the name of the fragment.
  fragment Viewer on User {
    # Initially, fetch the first 10 repositories. We'll show a "load more"
    # button to demostrate GraphQL connection cursors.
    repositories(first: 10) {
      # The only data we're using directly in this template is the total number
      # of repositories. Also note that its camelcase here.
      totalCount

      # Include data dependencies of app/views/repositories/_repositories.html.erb
      # All renders in this template will map to a fragment spread to
      # statically define the view composition relationship.
      ...Views::Repositories::Repositories::RepositoryConnection
    }
  }
%>
<%#
  The first step of any GraphQL defined view is to cast arguments to the locally
  defined fragment result wrapper. In a statically typed langauge, you can think
  of it as passing a concrete type into a function that accepts an interface.

    def repositories_index(viewer: Views::Repositories::Index::Viewer)

  The wrapper serves two primary roles:

  1. Provides Ruby friendly snake case accessors for accessing the underlying data
  2. Only expose fields explicitly defined by this fragment.
     `viewer.repositories` is a full set of data, but only `total_count` is
     exposed to this template since thats all we explicitly defined.
%>
<% viewer = Views::Repositories::Index::Viewer.new(viewer) %>

<div class="repositories">
  <ul class="list-group">
    <li class="list-group-item">
      <strong>Your repositories</strong>
      <%# NOTE: total_count is snake case here %>
      <span class="badge"><%= viewer.repositories.total_count %></span>
    </li>

    <%#
      render repositories subview passing along viewer.repositories
      See that Views::Repositories::Repositories::RepositoryConnection is
      declared in our static fragment.
    %>
    <%= render "repositories/repositories", repositories: viewer.repositories %>
  </ul>
</div>

app/views/repositories/show.html.erb
<%#
  GraphQL fragments are defined in the templates themselves.

  All data being used directly in this template should also be reflected
  statically in the fragment. And vice versa, all fields in the query fragment
  should only be used directly in this template. You MUST keep static queries
  and runtime usage in sync. Defining queries in the same file makes
  this aspect easier to manage.
%>
<%graphql
  # Fragments are parts of queries, they can't be executed themselves.
  # This fragment is defined on the Repository type and is coincidentally named
  # "Repository". You can name the fragment whatever you'd like. Its the name
  # that is exported as a Ruby constant, so it must start with a capital letter.
  #
  # Its exported as "Views::Repositories::Show::Repository". The module path to
  # the tempate then the name of the fragment.
  fragment Repository on Repository {
    # id is a GraphQL global id, not a database id
    # It is an opaque base64 identifier we can use to refetch the entity.
    id

    # owner is a User or Organization
    owner {
      login
    }

    # The repository's name
    name

    # Optional description text and homepage URL
    description
    homepageUrl

    # Include repositories/_navigation.html.erb data dependencies
    ...Views::Repositories::Navigation::Repository
  }
%>
<%#
  The first step of any GraphQL defined view is to cast arguments to the locally
  defined fragment result wrapper. In a statically typed langauge, you can think
  of it as passing a concrete type into a function that accepts an interface.

    def repositories_show(repository: Views::Repositories::Show::Repository)

  The wrapper serves two primary roles:

  1. Provides Ruby friendly snake case accessors for accessing the underlying data
  2. Only expose fields explicitly defined by this fragment.
     `repository` is a full set of data, but fields included by the
     ...Views::Repositories::Navigation::Repository spread are hidden.
%>
<% repository = Views::Repositories::Show::Repository.new(repository) %>

<div class="header clearfix">
  <%= render "repositories/navigation", repository: repository %>

  <h3 class="text-muted">
    <a href="<%= repositories_path %>"><%= repository.owner.login %></a>
    /
    <a href="<%= repository_path(repository.id) %>"><%= repository.name %></a>
  </h3>
</div>

<hr>

<div class="jumbotron">
  <h1><%= repository.name %></h1>

  <% if repository.description.present? %>
    <p><%= repository.description %></p>
  <% end %>

  <p>
    <%# NOTE: homepage_url is snake case here %>
    <% if repository.homepage_url.present? %>
      <a class="btn btn-primary btn-lg" href="<%= repository.homepage_url %>" role="button">Homepage</a>
    <% end %>

    <a class="btn btn-primary btn-lg" href="https://github.com/<%= repository.owner.login %>/<%= repository.name %>" role="button">View on GitHub</a>
  </p>
</div>